name: butter_extensions
description: Butter Extensions by Michael Frischbutter
version: 0.0.1
homepage: frischbutter.dev

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
